name: Help
description: なんでもお気軽にフィードバック下さいませ。
title: "[Help]: "
labels: ["help wanted"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        なんでもお気軽にフィードバック下さいませ。
  - type: textarea
    id: help-1
    attributes:
      label: hoge
      description: hoge
      placeholder:
      value:
    validations:
      required: true
